### ISSUE TITLE
Windows forewall rules are not removed by advfirewall unban actions

### ISSUE THREAD

**Issue by AndisGrossteins** [moteus/lua-spylog#8]
I discovered that advfirewall unban action does not remove the firewall rules created by ban action. This is because the UUID of unban action can't be used to identify firewall rules named with UUID of the ban action. That is to be expected because UUIDs are globally unique and are used to identify every action in database.

I played around with the idea to generate a new UUID and pass it as a parameter from jail but that does not work as I expected. I also could not find a way to pass the UUID of ban action to the unban action. I'm not too skilled in lua so I gave up.

The only workaround was to change naming of created firewall rules in advfirewall ban and unban actions:
```lua
local unban = 'netsh advfirewall firewall delete rule name="SpyLog <JAIL>:<FILTER>:<HOST>"'
local ban   = 'netsh advfirewall firewall add rule dir=in interface=any action=block ' ..
              'name="SpyLog <JAIL>:<FILTER>:<HOST>" description="<DATE> filter:<FILTER> jail:<JAIL> bantime:<BANTIME>" '   ..
              'remoteip="<HOST>/<NET>" localport="<PORT>" protocol="<PROTOCOL>" ';
```

**Comment by moteus** [comment]
Thanks for report.
Please try master branch.
I also found problem with pass parameters from jail.
e.g. when you pass 
```Lua
action   = {
    {"advfirewall",{unban = true; port = "5060,5080"; protocol = "udp"}};
  };
```
SpyLog does not apply default values for other parameters like `net` or `service`

I remember that I had some problem with long names for firewall rules.
This is why I do not add any additional info in it.
Also all rules have to have unique names.
